# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f'{m._get_name()}.onnx'
    torch.onnx.export(m, x, f)
    os.system(f'onnxslim {f} {f} && open {f}')  # pip install onnxslim
    ```
"""

from .block import (
    C1,
    C2,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C3Ghost,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    Multiin,
    IN,
    CPCA,
    CPCA_CF,
    FeatureAdd,
    PolarizedSelfAttention,
    Add,
    PolarizedSelfAttention_Channel,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, v10Detect
from .mamba_fusion import (
    AlignedLocalMambaFusion,
    BoostedGeometryRAAMambaFusion,
    CGSA,
    CGSA_Mamba,
    ConsistencyGuidedRAAMambaFusion,
    CrossModalMamba,
    GeometryPreservingRAAMambaFusion,
    ReliabilityAwareAlignedMambaFusion,
    ResidualConsistencyMambaFusion,
    ScheduledBoostedGeometryRAAMambaFusion,
    StabilizedRAAMambaFusion,
)
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "RepC3",
    "RTDETRDecoder",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "v10Detect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "AConv",
    "ELAN1",
    "RepVGGDW",
    "CIB",
    "C2fCIB",
    "Attention",
    "PSA",
    "SCDown",
    "Multiin",
    "IN",
    "CPCA",
    "FeatureAdd",
    "PolarizedSelfAttention",
    "Add",
    "PolarizedSelfAttention_Channel",
    "CPCA_CF",
    "CDFIM",
    "CGSA",
    "CrossModalMamba",
    "CGSA_Mamba",
    "AlignedLocalMambaFusion",
    "ConsistencyGuidedRAAMambaFusion",
    "ReliabilityAwareAlignedMambaFusion",
    "ResidualConsistencyMambaFusion",
    "ScheduledBoostedGeometryRAAMambaFusion",
    "StabilizedRAAMambaFusion",
    "GeometryPreservingRAAMambaFusion",
    "BoostedGeometryRAAMambaFusion",

)

CDFIM = CPCA_CF
